### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by hernikplays** [tpkowastaken/autojidelna#1]
Nemohl jsem si nevšimnout, že aplikace používá několik závislostí, nicméně to vypadá, že tahle aplikace je nepoužívá v souladu s jejich licencemi. Například canteenlib má licenci, která vyžaduje přikládat kopii licence při distribuci. Na to stačí pouhý [`showAboutDialog` ](https://api.flutter.dev/flutter/material/showAboutDialog.html) ([přiklad](https://git.mnau.xyz/hernik/opencanteen/src/commit/1950d850b857437ec00bf0e2b4e702b47f9869a2/lib/okna/jidelnicek.dart#L376-L389)). Ten obsahuje dialog s tlačítkem, které automaticky zobrazí licence všech použitých knihoven.

Pokud chcete aplikaci seriózně distribuovat, dával bych si na licence pozor.

**Comment by tpkowastaken** [comment]
díky, mrknu se na to

**Comment by tpkowastaken** [comment]
opraveno v [release v.1.0.2](https://github.com/tpkowastaken/autojidelna/releases/tag/v1.0.2)
